# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mwebd.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmwebd.proto\"\x0f\n\rStatusRequest\"d\n\x0eStatusResponse\x12\x1b\n\x13\x62lock_header_height\x18\x01 \x01(\x05\x12\x1a\n\x12mweb_header_height\x18\x02 \x01(\x05\x12\x19\n\x11mweb_utxos_height\x18\x03 \x01(\x05\"8\n\x0cUtxosRequest\x12\x13\n\x0b\x66rom_height\x18\x01 \x01(\x05\x12\x13\n\x0bscan_secret\x18\x02 \x01(\x0c\"I\n\x04Utxo\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x04\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x11\n\toutput_id\x18\x04 \x01(\t\"a\n\x0e\x41\x64\x64ressRequest\x12\x12\n\nfrom_index\x18\x01 \x01(\r\x12\x10\n\x08to_index\x18\x02 \x01(\r\x12\x13\n\x0bscan_secret\x18\x03 \x01(\x0c\x12\x14\n\x0cspend_pubkey\x18\x04 \x01(\x0c\"\"\n\x0f\x41\x64\x64ressResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x03(\t\"!\n\x0cSpentRequest\x12\x11\n\toutput_id\x18\x01 \x03(\t\"\"\n\rSpentResponse\x12\x11\n\toutput_id\x18\x01 \x03(\t\"t\n\rCreateRequest\x12\x0e\n\x06raw_tx\x18\x01 \x01(\x0c\x12\x13\n\x0bscan_secret\x18\x02 \x01(\x0c\x12\x14\n\x0cspend_secret\x18\x03 \x01(\x0c\x12\x17\n\x0f\x66\x65\x65_rate_per_kb\x18\x04 \x01(\x04\x12\x0f\n\x07\x64ry_run\x18\x05 \x01(\x08\"3\n\x0e\x43reateResponse\x12\x0e\n\x06raw_tx\x18\x01 \x01(\x0c\x12\x11\n\toutput_id\x18\x02 \x03(\t\"\"\n\x10\x42roadcastRequest\x12\x0e\n\x06raw_tx\x18\x01 \x01(\x0c\"!\n\x11\x42roadcastResponse\x12\x0c\n\x04txid\x18\x01 \x01(\t2\x88\x02\n\x03Rpc\x12)\n\x06Status\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\x12\x1f\n\x05Utxos\x12\r.UtxosRequest\x1a\x05.Utxo0\x01\x12.\n\tAddresses\x12\x0f.AddressRequest\x1a\x10.AddressResponse\x12&\n\x05Spent\x12\r.SpentRequest\x1a\x0e.SpentResponse\x12)\n\x06\x43reate\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\x12\x32\n\tBroadcast\x12\x11.BroadcastRequest\x1a\x12.BroadcastResponseB\x1bZ\x19github.com/ltcsuite/mwebdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mwebd_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031github.com/ltcsuite/mwebd'
  _globals['_STATUSREQUEST']._serialized_start=15
  _globals['_STATUSREQUEST']._serialized_end=30
  _globals['_STATUSRESPONSE']._serialized_start=32
  _globals['_STATUSRESPONSE']._serialized_end=132
  _globals['_UTXOSREQUEST']._serialized_start=134
  _globals['_UTXOSREQUEST']._serialized_end=190
  _globals['_UTXO']._serialized_start=192
  _globals['_UTXO']._serialized_end=265
  _globals['_ADDRESSREQUEST']._serialized_start=267
  _globals['_ADDRESSREQUEST']._serialized_end=364
  _globals['_ADDRESSRESPONSE']._serialized_start=366
  _globals['_ADDRESSRESPONSE']._serialized_end=400
  _globals['_SPENTREQUEST']._serialized_start=402
  _globals['_SPENTREQUEST']._serialized_end=435
  _globals['_SPENTRESPONSE']._serialized_start=437
  _globals['_SPENTRESPONSE']._serialized_end=471
  _globals['_CREATEREQUEST']._serialized_start=473
  _globals['_CREATEREQUEST']._serialized_end=589
  _globals['_CREATERESPONSE']._serialized_start=591
  _globals['_CREATERESPONSE']._serialized_end=642
  _globals['_BROADCASTREQUEST']._serialized_start=644
  _globals['_BROADCASTREQUEST']._serialized_end=678
  _globals['_BROADCASTRESPONSE']._serialized_start=680
  _globals['_BROADCASTRESPONSE']._serialized_end=713
  _globals['_RPC']._serialized_start=716
  _globals['_RPC']._serialized_end=980
# @@protoc_insertion_point(module_scope)
